name: Deploy Node App to EC2 (Docker)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: phuocpham
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/student-app || exit 1
            git pull origin main

            docker stop student-app || true
            docker rm student-app || true

            docker build -t student-app:latest .

            docker run -d \
              --name student-app \
              -p 80:3000 \
              -e APP_DB_HOST=localhost \
              -e APP_DB_USER=nodeapp \
              -e APP_DB_PASSWORD=student12 \
              -e APP_DB_NAME=STUDENTS \
              student-app:latest
